project_root: .
raw_daily_dir: ../shared_data/raw/daily/parquet_daily_cache
model_dir: outputs/models/baseline_lgbm_no_runupscore7_w150
output_path: outputs/predictions/scan_predictions_lgbm_baseline_no_runupscore7_w150.csv
window_size: 150
min_history: 1
