project_root: .
lgbm_config: configs/infer_lgbm_baseline_runupscore7_w150.yaml
xgb_config: configs/infer_xgb_baseline_runupscore7_w150.yaml
output_path: outputs/predictions/scan_predictions_intersection_top50_baseline_runupscore7_w150.csv
top_n: 50
